### PR TITLE
Storage Improvements

### LINKED ISSUE #109: Connection pooling issue when using the H2 database
If I try to do certain querying commands, particularly with large radii I get this exception printed to the console every second:

```
[00:40:05 ERROR] [STDERR]: java.sql.SQLTransientConnectionException: HikariPool-2 - Connection is not available, request timed out after 30000ms.
[00:40:05 ERROR] [STDERR]:      at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:601)
[00:40:05 ERROR] [STDERR]:      at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
[00:40:05 ERROR] [STDERR]:      at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
[00:40:05 ERROR] [STDERR]:      at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
[00:40:05 ERROR] [STDERR]:      at com.helion3.prism.storage.h2.H2StorageAdapter.getConnection(H2StorageAdapter.java:60)
[00:40:05 ERROR] [STDERR]:      at com.helion3.prism.storage.h2.H2Records.write(H2Records.java:67)
[00:40:05 ERROR] [STDERR]:      at com.helion3.prism.queues.RecordingQueueManager.run(RecordingQueueManager.java:50)
[00:40:05 ERROR] [STDERR]:      at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
[00:40:05 ERROR] [STDERR]:      at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186)
[00:40:05 ERROR] [STDERR]:      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:40:05 ERROR] [STDERR]:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:40:05 ERROR] [STDERR]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:40:05 ERROR] [STDERR]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:40:05 ERROR] [STDERR]:      at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by LXGaming**
Relocate mongodb and bson
Add configurable pool sizes
Setup Hikari for H2
Add SQL purging
Fix Mongo Deprecated method

Should fix #109 as H2 should now have multiple connections.

### CODE REVIEW

File: src/main/java/com/helion3/prism/storage/mysql/MySQLStorageAdapter.java [hunk 1]
```diff
@@ -129,6 +144,82 @@ protected void createTables() throws SQLException {
...
+        }
+    }
+    
+    /**
+     * Removes extra record information if the parent record doesn't exist
+     *
+     * @return The amount of rows removed.
+     * @throws Exception
+     */
+    protected int purgeExtra() throws Exception {
```
Comment (viveleroi) [inline src/main/java/com/helion3/prism/storage/mysql/MySQLStorageAdapter.java]: This method (for both MySQL and H2 variations) shouldn't be required because the create table sql has a foreign key/delete cascade statements:

- [H2](https://github.com/prism/Prism/blob/master/src/main/java/com/helion3/prism/storage/h2/H2StorageAdapter.java#L105-L107)
- [MySQL](https://github.com/prism/Prism/blob/master/src/main/java/com/helion3/prism/storage/mysql/MySQLStorageAdapter.java#L124-L126)

If the primary record is deleted it should automatically delete the extra records.

**Review by viveleroi — CHANGES_REQUESTED** [review]

File: src/main/java/com/helion3/prism/storage/mysql/MySQLStorageAdapter.java (hunk 1 above)
Comment (LXGaming) [reply src/main/java/com/helion3/prism/storage/mysql/MySQLStorageAdapter.java]: Ah, Good point

**Review by viveleroi — APPROVED** [review]

**Comment by viveleroi** [comment]
Looks fine, have you been able to test the changes, primarily the purge logic?

**Comment by LXGaming** [comment]
I've tested the purge logic on H2 and MySQL with databases between 50 ~ 100mb in size (About 200000 rows) works without issues
